In [2]:
import torch
torch.__version__

'2.8.0+cpu'

In [3]:
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.shape)
print(scalar.item())

tensor(7)
0
torch.Size([])
7


In [4]:
vector = torch.tensor([7, 2, 3])
print(vector)
print(vector.ndim)
print(vector.shape)
print(vector[0].item())
print(vector[1].item())
print(vector[2].item())

tensor([7, 2, 3])
1
torch.Size([3])
7
2
3


In [5]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)


tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [6]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])


In [7]:
# Tensor
TENSOR1 = torch.tensor([[[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]]])
print(TENSOR1)
print(TENSOR1.ndim)
print(TENSOR1.shape)

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]])
4
torch.Size([1, 1, 3, 3])


In [8]:
def aslist(x: torch.Tensor):
    return x.tolist()

def cast(x: list[torch.Tensor]) -> list:
    cache = []
    for item in x:
        cache.append(item.tolist())

    return cache

In [9]:
print('\n#### Vector ####')
v1 = torch.tensor([1, 2, 3])
v2 = torch.tensor([4, 5, 6])
v3 = torch.tensor([7, 8, 9])
print(v1)
print(v2)
print(v3)

print('\n#### Matrix ####')
m1 = torch.tensor(cast([v1, v2, v3]))
m2 = torch.tensor(cast([v1, v2, v3]))
m3 = torch.tensor(cast([v1, v2, v3]))

print(f"m1: {m1}, dimention: {m1.ndim}")
print(f"m2: {m2}, dimention: {m2.ndim}")
print(f"m3: {m3}, dimention: {m3.ndim}")



#### Vector ####
tensor([1, 2, 3])
tensor([4, 5, 6])
tensor([7, 8, 9])

#### Matrix ####
m1: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), dimention: 2
m2: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), dimention: 2
m3: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), dimention: 2


In [10]:
print('\n#### Tensor ####')

X = [cast(v1), cast(v2), cast(v3)]
TENSORX = torch.tensor([X, X], dtype=torch.half)

print(TENSORX)
print(TENSORX.ndim)
print(TENSORX.shape)
print(TENSORX.dtype)



#### Tensor ####
tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]],

        [[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]], dtype=torch.float16)
3
torch.Size([2, 3, 3])
torch.float16


In [41]:
tensor = torch.tensor([1, 2, 3])
print(tensor)
print(tensor + 10)
print(tensor * 10)

print(tensor * tensor)
print(torch.matmul(tensor, tensor)) # matrix multiplication
print(tensor @ tensor) # alternate syntax for matrix multiplication

## transformation
print(tensor.unsqueeze(0))
print(tensor.unsqueeze(0).T)


tensor([1, 2, 3])
tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([1, 4, 9])
tensor(14)
tensor(14)
tensor([[1, 2, 3]])
tensor([[1],
        [2],
        [3]])


In [45]:
x = torch.arange(1., 8.)
print(x)
print(x.shape)

z = x.view(1, 7)
print(z)

z[:, 0] = 5
print(x)
print(z)

x_stacked = torch.stack([x, x, x, x], dim=0)
print(x_stacked)

tensor([1., 2., 3., 4., 5., 6., 7.])
torch.Size([7])
tensor([[1., 2., 3., 4., 5., 6., 7.]])
tensor([5., 2., 3., 4., 5., 6., 7.])
tensor([[5., 2., 3., 4., 5., 6., 7.]])
tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])


In [48]:
x_original = torch.rand(size=(224, 224, 3))
print(x_original)
print(x_original.shape)
x_permuted = x_original.permute(2, 0, 1)
print(x_permuted)
print(x_permuted.shape)

tensor([[[0.9369, 0.0408, 0.4402],
         [0.5188, 0.6994, 0.1101],
         [0.9700, 0.3302, 0.8026],
         ...,
         [0.3954, 0.9984, 0.3450],
         [0.4352, 0.1768, 0.1390],
         [0.2362, 0.8701, 0.6512]],

        [[0.4891, 0.2733, 0.5540],
         [0.9026, 0.1093, 0.0424],
         [0.3570, 0.2743, 0.8322],
         ...,
         [0.7102, 0.1343, 0.1262],
         [0.1262, 0.7728, 0.4758],
         [0.8093, 0.4239, 0.4750]],

        [[0.5841, 0.9506, 0.7401],
         [0.6989, 0.6231, 0.0286],
         [0.9729, 0.8127, 0.2674],
         ...,
         [0.3734, 0.3504, 0.8560],
         [0.5894, 0.2820, 0.1543],
         [0.7900, 0.8549, 0.9922]],

        ...,

        [[0.3454, 0.2064, 0.1875],
         [0.6604, 0.5172, 0.4040],
         [0.3419, 0.2239, 0.2656],
         ...,
         [0.7306, 0.2186, 0.5314],
         [0.8557, 0.3874, 0.4318],
         [0.6846, 0.4904, 0.9319]],

        [[0.2235, 0.0151, 0.1487],
         [0.6263, 0.2763, 0.0906],
         [0.

In [89]:
x = torch.arange(1, 10).reshape(1, 3, 3) # reshape(batch-size, row, column)
print(x)
print(x.shape)

y = x.permute(0, 1, 2)
print('\n0, 1, 2')
print(y)
print(y.shape)

y = x.permute(0, 2, 1)
print('\n0, 2, 1')
print(y)
print(y.shape)

y = x.permute(1, 2, 0)
print('\n1, 2, 0')
print(y)
print(y.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([1, 3, 3])

0, 1, 2
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([1, 3, 3])

0, 2, 1
tensor([[[1, 4, 7],
         [2, 5, 8],
         [3, 6, 9]]])
torch.Size([1, 3, 3])

1, 2, 0
tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])
torch.Size([3, 3, 1])


In [110]:
x = torch.arange(1, 10).reshape(1, 3, 3) # reshape(batch-size, row, column)
print(x)
print(x.shape)
print('\n')
y = x.squeeze(0)
print(y)
print(y.shape)
print(y.permute(1, 0))

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([1, 3, 3])


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


In [123]:
x = torch.arange(1, 10).reshape(1, 3, 3) # reshape(batch-size, row, column)
print(x)
print(x[:, 0])
print(x[:, :, 0])
y = x.squeeze(0)
print(y)
print(y[:, 0]) # all rows 0th column
print(y[0, :]) # 0th row all column

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3]])
tensor([[1, 4, 7]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 4, 7])
tensor([1, 2, 3])
