In [1]:
s = "Lexora"
it = iter(s)

print(next(it))  # L
print(next(it))  # e
print(next(it))  # x

L
e
x


In [2]:
class EvenNumbers:
    def __iter__(self):
        self.n = 2
        return self

    def __next__(self):
        x = self.n
        self.n += 2
        return x

even = EvenNumbers()
it = iter(even)

for _ in range(5):
    print(next(it))  # 2, 4, 6, 8, 10

2
4
6
8
10


In [3]:
li = [100, 200, 300]
it = iter(li)

while True:
    try:
        print(next(it))
    except StopIteration:
        print("End of iteration")
        break

100
200
300
End of iteration


In [4]:
books = ["Lexora", "VersOne", "Epubify"]

for index, name in enumerate(books):
    print(f"{index}: {name}")

0: Lexora
1: VersOne
2: Epubify


In [9]:
description = """
Lexora is a beautifully crafted EPUB reader.
It supports AI-powered chat, accessibility features,
and elegant UI themes for immersive reading.
"""
print(description)

description2 = f"""
Lexora is a beautifully crafted EPUB reader.
It supports AI-powered chat, accessibility features,
and elegant UI themes for immersive reading.
{description}
"""
print(description2)



Lexora is a beautifully crafted EPUB reader.
It supports AI-powered chat, accessibility features,
and elegant UI themes for immersive reading.


Lexora is a beautifully crafted EPUB reader.
It supports AI-powered chat, accessibility features,
and elegant UI themes for immersive reading.

Lexora is a beautifully crafted EPUB reader.
It supports AI-powered chat, accessibility features,
and elegant UI themes for immersive reading.




In [2]:
query = "SELECT * FROM books WHERE " \
        "author = 'Mahabubul' AND " \
        "published_year > 2020"
print(query)

SELECT * FROM books WHERE author = 'Mahabubul' AND published_year > 2020


In [3]:
message = (
    "Welcome to Lexora. "
    "Your personalized reading experience starts here. "
    "Enjoy AI-powered insights and elegant design."
)
print(message)

Welcome to Lexora. Your personalized reading experience starts here. Enjoy AI-powered insights and elegant design.


In [6]:
lines = [
    "Chapter 1: The Awakening",
    "Chapter 2: The Journey",
    "Chapter 3: The Revelation"
]
book_outline = "\n".join(lines)
print(book_outline)

Chapter 1: The Awakening
Chapter 2: The Journey
Chapter 3: The Revelation


In [5]:
import textwrap

html = textwrap.dedent("""
    <div class="chapter">
        <h1>Introduction</h1>
        <p>Welcome to Lexora.</p>
    </div>
""")

print(html)


<div class="chapter">
    <h1>Introduction</h1>
    <p>Welcome to Lexora.</p>
</div>



In [10]:
import numpy as np
np.random.seed(47)

x = np.random.random((2, 1))
print(x)

y = 0.2 * x
print(y)

z = y - 0.1
print(z)

print(z.T)
# weight_0_1 = 0.2 * np.random.random((len(vocab), hidden_size)) - 0.1

[[0.11348847]
 [0.97448309]]
[[0.02269769]
 [0.19489662]]
[[-0.07730231]
 [ 0.09489662]]
[[-0.07730231  0.09489662]]


In [ ]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

z = np.outer(x, y)
print(z)

print(np.sum(z, axis=0))
print(np.sum(z, axis=1))
print()
zz = np.expand_dims(z, 1) # equivalent of torch.unsqueeze(1)
print(zz)
print(np.sum(zz, axis=2))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[24 30 36]
[15 30 45]

[[[ 4  5  6]]

 [[ 8 10 12]]

 [[12 15 18]]]
[[15]
 [30]
 [45]]
