In [2]:
import torch
torch.__version__

'2.8.0+cpu'

In [12]:
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.shape)
print(scalar.item())

tensor(7)
0
torch.Size([])
7


In [18]:
vector = torch.tensor([7, 2, 3])
print(vector)
print(vector.ndim)
print(vector.shape)
print(vector[0].item())
print(vector[1].item())
print(vector[2].item())

tensor([7, 2, 3])
1
torch.Size([3])
7
2
3


In [22]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)


tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [24]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])


In [25]:
# Tensor
TENSOR1 = torch.tensor([[[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]]])
print(TENSOR1)
print(TENSOR1.ndim)
print(TENSOR1.shape)

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]])
4
torch.Size([1, 1, 3, 3])


In [38]:
def aslist(x: torch.Tensor):
    return x.tolist()

def cast(x: list[torch.Tensor]) -> list:
    cache = []
    for item in x:
        cache.append(item.tolist())

    return cache

In [50]:
print('\n#### Vector ####')
v1 = torch.tensor([1, 2, 3])
v2 = torch.tensor([4, 5, 6])
v3 = torch.tensor([7, 8, 9])
print(v1)
print(v2)
print(v3)

print('\n#### Matrix ####')
m1 = torch.tensor(cast([v1, v2, v3]))
m2 = torch.tensor(cast([v1, v2, v3]))
m3 = torch.tensor(cast([v1, v2, v3]))

print(f"m1: {m1}, dimention: {m1.ndim}")
print(f"m2: {m2}, dimention: {m2.ndim}")
print(f"m3: {m3}, dimention: {m3.ndim}")



#### Vector ####
tensor([1, 2, 3])
tensor([4, 5, 6])
tensor([7, 8, 9])

#### Matrix ####
m1: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), dimention: 2
m2: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), dimention: 2
m3: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), dimention: 2


In [67]:
print('\n#### Tensor ####')

X = [cast(v1), cast(v2), cast(v3)]
TENSORX = torch.tensor([X, X], dtype=torch.half)

print(TENSORX)
print(TENSORX.ndim)
print(TENSORX.shape)
print(TENSORX.dtype)



#### Tensor ####
tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]],

        [[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]], dtype=torch.float16)
3
torch.Size([2, 3, 3])
torch.float16
